### Suspect location query
POST https://hub.ag3nts.org/api/location
Content-Type: application/json

{
  "apikey": "{{$dotenv AI_DEVS_API_KEY}}",
  "name": "Jacek",
  "surname": "Nowak"
}

# Answer example:
# [
#   {
#     "latitude": 50.232,
#     "longitude": 19.152
#   },
#   {
#     "latitude": 50.452,
#     "longitude": 18.851
#   },
#   ...
# ]


### Suspect access level query
POST https://hub.ag3nts.org/api/accesslevel
Content-Type: application/json

{
  "apikey": "{{$dotenv AI_DEVS_API_KEY}}",
  "name": "Cezary",
  "surname": "Żurek",
  "birthYear": 1987
}

# Answer example:
# {
#   "name": "Cezary",
#   "surname": "Żurek",
#   "accessLevel": 1
# }

### Powerplants locations query
GET https://hub.ag3nts.org/data/{{$dotenv AI_DEVS_API_KEY}}/findhim_locations.json

# Answer example:
# {
#   "power_plants": {
#     "Zabrze": {
#       "is_active": true,
#       "power": "35 MW",
#       "code": "PWR3847PL"
#     },
#     "Piotrków Trybunalski": {
#       "is_active": true,
#       "power": "28 MW",
#       "code": "PWR5921PL"
#     },
#     ...
#   }
# }

### Verify answer
POST https://hub.ag3nts.org/verify
Content-Type: application/json

{
  "apikey": "{{$dotenv AI_DEVS_API_KEY}}",
  "task": "findhim",
  "answer": {
    "name": "Cezary",
    "surname": "Żurek",
    "accessLevel": 3,
    "powerPlant": "PWR1234PL"
  }
}

# Answer example:
# {
#   "code": 200,
#   "message": "Yes, he is! FLAG{1234}"
# }

### Geocoding query
GET https://nominatim.openstreetmap.org/search?q=Nowy+Sącz&format=json

# Answer example:
# [
#   {
#     "place_id": 175913125,
#     "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
#     "osm_type": "relation",
#     "osm_id": 2904794,
#     "lat": "49.6103040",
#     "lon": "20.7149366",
#     "class": "boundary",
#     "type": "administrative",
#     "place_rank": 14,
#     "importance": 0.5756975533927072,
#     "addresstype": "administrative",
#     "name": "Nowy Sącz",
#     "display_name": "Nowy Sącz, gmina Chełmiec, województwo małopolskie, Polska",
#     "boundingbox": [
#       "49.5549437",
#       "49.6655553",
#       "20.6484062",
#       "20.7648749"
#     ]
#   },
#   ...
# ] 
    