### Pobieranie lokalizacji dla podejrzanego
POST https://hub.ag3nts.org/api/location
Content-Type: application/json

{
  "apikey": "{{$dotenv AI_DEVS_API_KEY}}",
  "name": "Jacek",
  "surname": "Nowak"
}

### Odpowidź ma format:
# [
#   {
#     "latitude": 50.232,
#     "longitude": 19.152
#   },
#   ... 
# ]


### Pobieranie uprawnień dla podejrzanego
POST https://hub.ag3nts.org/api/accesslevel
Content-Type: application/json

{
  "apikey": "{{$dotenv AI_DEVS_API_KEY}}",
  "name": "Jacek",
  "surname": "Nowak",
  "birthYear": 1991
}
###
POST https://hub.ag3nts.org/api/accesslevel
Content-Type: application/json

{
  "apikey": "{{$dotenv AI_DEVS_API_KEY}}",
  "name": "Cezary",
  "surname": "Żurek",
  "birthYear": 1987
}

###
GET https://nominatim.openstreetmap.org/search?q=Nowy+Sącz&format=json



    

    

### Odpowidź ma format:
# {
#   "name": "Jacek",
#   "surname": "Nowak",
#   "accessLevel": 1
# }


