// tools/definitions.js

export const agentTools = [
  {
    type: "function",
    function: {
      name: "get_suspects",
      description: "Retrieves the list of suspected individuals. Returns a JSON array of objects containing 'name', 'surname', and 'birthYear'.",
      parameters: {
        type: "object",
        properties: {},
        required: []
      }
    }
  },
  {
    type: "function",
    function: {
      name: "get_power_plants",
      description: "Retrieves the list of power plants. Returns a JSON object mapping power plant IDs to their geographic coordinates.",
      parameters: {
        type: "object",
        properties: {},
        required: []
      }
    }
  },
  {
    type: "function",
    function: {
      name: "download_people_locations",
      description: "Fetches location history for a provided list of people and saves them to the workspace. Returns a JSON array of generated filenames containing the location data.",
      parameters: {
        type: "object",
        properties: {
          people: {
            type: "array",
            description: "List of people to track.",
            items: {
              type: "object",
              properties: {
                name: { type: "string" },
                surname: { type: "string" }
              },
              required: ["name", "surname"]
            }
          }
        },
        required: ["people"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "analyze_proximity",
      description: "Analyzes geographic distance between power plants and people's locations. Returns a JSON object identifying the closest person, distance, and the corresponding powerPlantId.",
      parameters: {
        type: "object",
        properties: {
          locations_filenames: {
            type: "array",
            items: { type: "string" },
            description: "Array of filenames generated by the download_people_locations tool."
          },
          power_plants_data: {
            type: "object",
            description: "The JSON object containing power plants data retrieved from the get_power_plants tool."
          }
        },
        required: ["locations_filenames", "power_plants_data"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "get_access_level",
      description: "Retrieves the security access level for a specific person. Returns an integer representing the access level.",
      parameters: {
        type: "object",
        properties: {
          name: { type: "string" },
          surname: { type: "string" },
          birthYear: { type: "integer" }
        },
        required: ["name", "surname", "birthYear"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "submit_task",
      description: "Submits the final investigation report to HQ. Returns the flag if successful.",
      parameters: {
        type: "object",
        properties: {
          name: { type: "string" },
          surname: { type: "string" },
          accessLevel: { type: "integer" },
          powerPlant: { type: "string" }
        },
        required: ["name", "surname", "accessLevel", "powerPlant"]
      }
    }
  }
];